spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/talkAboutAnything
    username: seongheon
    password: qwer1234
  jpa:
    hibernate:
      # ??????? none , validate
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # 세션id 분산저장을 위한 설정
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    timeout: 1800s
    redis:
      namespace: spring:session


  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html
    cache: false

  devtools:
    livereload:
      enabled: true

logging:
  level:
    org.springframework.security: INFO