spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devicemanager
    username: seongheon
    password: qwer1234
  jpa:
    hibernate:
      # ??????? none , validate
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect