version: "3"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: seongheon
      POSTGRES_PASSWORD: qwer1234
      POSTGRES_DB: talkAboutAnything
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data